config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :help_sessions
  resources :help_session_requests
  resources :completed_courses
  resources :availabilities
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :reviews
  resources :courses
  resources :universities
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
end

app/models/completed_course.rb
class CompletedCourse < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/help_session.rb
class HelpSession < ApplicationRecord
end

app/models/help_session_request.rb
class HelpSessionRequest < ApplicationRecord
    attr_accessor :user_name
    attr_accessor :tutor_name
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/university.rb
class University < ApplicationRecord
    mount_uploader :avatar, AvatarUploader

    validates_presence_of   :avatar
    validates_integrity_of  :avatar
    validates_processing_of :avatar
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  attr_accessor :rating
  attr_accessor :reviews
  attr_accessor :price
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/help_sessions_controller.rb
class HelpSessionsController < ApplicationController
  before_action :set_help_session, only: [:show, :edit, :update, :destroy]

  # GET /help_sessions
  # GET /help_sessions.json
  def index
    @help_sessions = HelpSession.all
  end

  # GET /help_sessions/1
  # GET /help_sessions/1.json
  def show
  end

  # GET /help_sessions/new
  def new
    @help_session = HelpSession.new
  end

  # GET /help_sessions/1/edit
  def edit
  end

  # POST /help_sessions
  # POST /help_sessions.json
  def create
    @help_session = HelpSession.new(help_session_params)

    respond_to do |format|
      if @help_session.save
        format.html { redirect_to @help_session, notice: 'Help session was successfully created.' }
        format.json { render :show, status: :created, location: @help_session }
      else
        format.html { render :new }
        format.json { render json: @help_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /help_sessions/1
  # PATCH/PUT /help_sessions/1.json
  def update
    respond_to do |format|
      if @help_session.update(help_session_params)
        format.html { redirect_to @help_session, notice: 'Help session was successfully updated.' }
        format.json { render :show, status: :ok, location: @help_session }
      else
        format.html { render :edit }
        format.json { render json: @help_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /help_sessions/1
  # DELETE /help_sessions/1.json
  def destroy
    @help_session.destroy
    respond_to do |format|
      format.html { redirect_to help_sessions_url, notice: 'Help session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help_session
      @help_session = HelpSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_session_params
      params.require(:help_session).permit(:user_id, :tutor_id, :course_id, :user_started, :tutor_started, :started_at, :user_ended, :tutor_ended, :ended_at, :start, :end, :cancelled, :cancelled_by, :message)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @users }
      end
    end
  
    def show
      @user = User.find(params[:id])
      @reviews = Review.where(user_id: params[:id])
      @availabilities = Availability.where(user_id: params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    end
  end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def week_days
        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/help_sessions_helper.rb
module HelpSessionsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/help_sessions/_form.html.erb
<%= form_with(model: help_session, local: true) do |form| %>
  <% if help_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help_session.errors.count, "error") %> prohibited this help_session from being saved:</h2>

      <ul>
      <% help_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :help_session_user_id %>
  </div>

  <div class="field">
    <%= form.label :tutor_id %>
    <%= form.number_field :tutor_id, id: :help_session_tutor_id %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id, id: :help_session_course_id %>
  </div>

  <div class="field">
    <%= form.label :user_started %>
    <%= form.check_box :user_started, id: :help_session_user_started %>
  </div>

  <div class="field">
    <%= form.label :tutor_started %>
    <%= form.check_box :tutor_started, id: :help_session_tutor_started %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at, id: :help_session_started_at %>
  </div>

  <div class="field">
    <%= form.label :user_ended %>
    <%= form.check_box :user_ended, id: :help_session_user_ended %>
  </div>

  <div class="field">
    <%= form.label :tutor_ended %>
    <%= form.check_box :tutor_ended, id: :help_session_tutor_ended %>
  </div>

  <div class="field">
    <%= form.label :ended_at %>
    <%= form.datetime_select :ended_at, id: :help_session_ended_at %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start, id: :help_session_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end, id: :help_session_end %>
  </div>

  <div class="field">
    <%= form.label :cancelled %>
    <%= form.check_box :cancelled, id: :help_session_cancelled %>
  </div>

  <div class="field">
    <%= form.label :cancelled_by %>
    <%= form.number_field :cancelled_by, id: :help_session_cancelled_by %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :help_session_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/help_sessions/edit.html.erb
<h1>Editing Help Session</h1>

<%= render 'form', help_session: @help_session %>

<%= link_to 'Show', @help_session %> |
<%= link_to 'Back', help_sessions_path %>

app/views/help_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Help Sessions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Tutor</th>
      <th>Course</th>
      <th>User started</th>
      <th>Tutor started</th>
      <th>Started at</th>
      <th>User ended</th>
      <th>Tutor ended</th>
      <th>Ended at</th>
      <th>Start</th>
      <th>End</th>
      <th>Cancelled</th>
      <th>Cancelled by</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @help_sessions.each do |help_session| %>
      <tr>
        <td><%= help_session.user_id %></td>
        <td><%= help_session.tutor_id %></td>
        <td><%= help_session.course_id %></td>
        <td><%= help_session.user_started %></td>
        <td><%= help_session.tutor_started %></td>
        <td><%= help_session.started_at %></td>
        <td><%= help_session.user_ended %></td>
        <td><%= help_session.tutor_ended %></td>
        <td><%= help_session.ended_at %></td>
        <td><%= help_session.start %></td>
        <td><%= help_session.end %></td>
        <td><%= help_session.cancelled %></td>
        <td><%= help_session.cancelled_by %></td>
        <td><%= help_session.message %></td>
        <td><%= link_to 'Show', help_session %></td>
        <td><%= link_to 'Edit', edit_help_session_path(help_session) %></td>
        <td><%= link_to 'Destroy', help_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Help Session', new_help_session_path %>

app/views/help_sessions/new.html.erb
<h1>New Help Session</h1>

<%= render 'form', help_session: @help_session %>

<%= link_to 'Back', help_sessions_path %>

app/views/help_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @help_session.user_id %>
</p>

<p>
  <strong>Tutor:</strong>
  <%= @help_session.tutor_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @help_session.course_id %>
</p>

<p>
  <strong>User started:</strong>
  <%= @help_session.user_started %>
</p>

<p>
  <strong>Tutor started:</strong>
  <%= @help_session.tutor_started %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @help_session.started_at %>
</p>

<p>
  <strong>User ended:</strong>
  <%= @help_session.user_ended %>
</p>

<p>
  <strong>Tutor ended:</strong>
  <%= @help_session.tutor_ended %>
</p>

<p>
  <strong>Ended at:</strong>
  <%= @help_session.ended_at %>
</p>

<p>
  <strong>Start:</strong>
  <%= @help_session.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @help_session.end %>
</p>

<p>
  <strong>Cancelled:</strong>
  <%= @help_session.cancelled %>
</p>

<p>
  <strong>Cancelled by:</strong>
  <%= @help_session.cancelled_by %>
</p>

<p>
  <strong>Message:</strong>
  <%= @help_session.message %>
</p>

<%= link_to 'Edit', edit_help_session_path(@help_session) %> |
<%= link_to 'Back', help_sessions_path %>