config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :help_sessions
  resources :help_session_requests
  resources :completed_courses
  resources :availabilities
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :reviews
  resources :courses
  resources :universities
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
end

app/models/completed_course.rb
class CompletedCourse < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/help_session.rb
class HelpSession < ApplicationRecord
end

app/models/help_session_request.rb
class HelpSessionRequest < ApplicationRecord
    attr_accessor :user_name
    attr_accessor :tutor_name
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/university.rb
class University < ApplicationRecord
    mount_uploader :avatar, AvatarUploader

    validates_presence_of   :avatar
    validates_integrity_of  :avatar
    validates_processing_of :avatar
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  attr_accessor :rating
  attr_accessor :reviews
  attr_accessor :price
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:from_user_id, :to_user_id, :help_session_id, :amount, :tip, :completed, :proof)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @users }
      end
    end
  
    def show
      @user = User.find(params[:id])
      @reviews = Review.where(user_id: params[:id])
      @availabilities = Availability.where(user_id: params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    end
  end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def week_days
        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/help_sessions_helper.rb
module HelpSessionsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :from_user_id %>
    <%= form.number_field :from_user_id, id: :payment_from_user_id %>
  </div>

  <div class="field">
    <%= form.label :to_user_id %>
    <%= form.number_field :to_user_id, id: :payment_to_user_id %>
  </div>

  <div class="field">
    <%= form.label :help_session_id %>
    <%= form.number_field :help_session_id, id: :payment_help_session_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :payment_amount %>
  </div>

  <div class="field">
    <%= form.label :tip %>
    <%= form.text_field :tip, id: :payment_tip %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed, id: :payment_completed %>
  </div>

  <div class="field">
    <%= form.label :proof %>
    <%= form.text_field :proof, id: :payment_proof %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>From user</th>
      <th>To user</th>
      <th>Help session</th>
      <th>Amount</th>
      <th>Tip</th>
      <th>Completed</th>
      <th>Proof</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.from_user_id %></td>
        <td><%= payment.to_user_id %></td>
        <td><%= payment.help_session_id %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.tip %></td>
        <td><%= payment.completed %></td>
        <td><%= payment.proof %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From user:</strong>
  <%= @payment.from_user_id %>
</p>

<p>
  <strong>To user:</strong>
  <%= @payment.to_user_id %>
</p>

<p>
  <strong>Help session:</strong>
  <%= @payment.help_session_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Tip:</strong>
  <%= @payment.tip %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @payment.completed %>
</p>

<p>
  <strong>Proof:</strong>
  <%= @payment.proof %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>