config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :help_sessions
  resources :help_session_requests
  resources :completed_courses
  resources :availabilities
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :reviews
  resources :courses
  resources :universities
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
end

app/models/completed_course.rb
class CompletedCourse < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/help_session.rb
class HelpSession < ApplicationRecord
end

app/models/help_session_request.rb
class HelpSessionRequest < ApplicationRecord
    attr_accessor :user_name
    attr_accessor :tutor_name
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/university.rb
class University < ApplicationRecord
    mount_uploader :avatar, AvatarUploader

    validates_presence_of   :avatar
    validates_integrity_of  :avatar
    validates_processing_of :avatar
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  attr_accessor :rating
  attr_accessor :reviews
  attr_accessor :price
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :reviewer_user_id, :rating, :notes)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @users }
      end
    end
  
    def show
      @user = User.find(params[:id])
      @reviews = Review.where(user_id: params[:id])
      @availabilities = Availability.where(user_id: params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    end
  end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def week_days
        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/help_sessions_helper.rb
module HelpSessionsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :review_user_id %>
  </div>

  <div class="field">
    <%= form.label :reviewer_user_id %>
    <%= form.number_field :reviewer_user_id, id: :review_reviewer_user_id %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :review_rating %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes, id: :review_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Reviewer user</th>
      <th>Rating</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user_id %></td>
        <td><%= review.reviewer_user_id %></td>
        <td><%= review.rating %></td>
        <td><%= review.notes %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Reviewer user:</strong>
  <%= @review.reviewer_user_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @review.notes %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>