config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :help_sessions
  resources :help_session_requests
  resources :completed_courses
  resources :availabilities
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :reviews
  resources :courses
  resources :universities
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
end

app/models/completed_course.rb
class CompletedCourse < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/help_session.rb
class HelpSession < ApplicationRecord
end

app/models/help_session_request.rb
class HelpSessionRequest < ApplicationRecord
    attr_accessor :user_name
    attr_accessor :tutor_name
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/university.rb
class University < ApplicationRecord
    mount_uploader :avatar, AvatarUploader

    validates_presence_of   :avatar
    validates_integrity_of  :avatar
    validates_processing_of :avatar
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  attr_accessor :rating
  attr_accessor :reviews
  attr_accessor :price
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/help_session_requests_controller.rb
class HelpSessionRequestsController < ApplicationController
  before_action :set_help_session_request, only: [:show, :edit, :update, :destroy]

  # GET /help_session_requests
  # GET /help_session_requests.json
  def index
    @help_session_requests = HelpSessionRequest.all
  end

  # GET /help_session_requests/1
  # GET /help_session_requests/1.json
  def show

  end

  # GET /help_session_requests/new
  def new
    @help_session_request = HelpSessionRequest.new
  end

  # GET /help_session_requests/1/edit
  def edit
  end

  # POST /help_session_requests
  # POST /help_session_requests.json
  def create
    @help_session_request = HelpSessionRequest.new(user_id: params[:user_id], tutor_id: params[:tutor_id], course_id: params[:course_id], start: params[:start], end: params[:end])

    respond_to do |format|
      if @help_session_request.save
        format.html { redirect_to user_path(id: params[:tutor_id]), notice: 'Sent Request!' }
        format.json { render :show, status: :created, location: @help_session_request }
      else
        # format.html { render :new }
        # format.json { render json: @help_session_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /help_session_requests/1
  # PATCH/PUT /help_session_requests/1.json
  def update
    respond_to do |format|
      if @help_session_request.update(help_session_request_params)
        format.html { redirect_to @help_session_request, notice: 'Help session request was successfully updated.' }
        format.json { render :show, status: :ok, location: @help_session_request }
      else
        format.html { render :edit }
        format.json { render json: @help_session_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /help_session_requests/1
  # DELETE /help_session_requests/1.json
  def destroy
    @help_session_request.destroy
    respond_to do |format|
      format.html { redirect_to help_session_requests_url, notice: 'Help session request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help_session_request
      @help_session_request = HelpSessionRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_session_request_params
      params.require(:help_session_request).permit(:user_id, :tutor_id, :course_id, :start, :end, :accepted, :denied, :denied_by, :message)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @users }
      end
    end
  
    def show
      @user = User.find(params[:id])
      @reviews = Review.where(user_id: params[:id])
      @availabilities = Availability.where(user_id: params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    end
  end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def week_days
        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/help_session_requests_helper.rb
module HelpSessionRequestsHelper
end

app/helpers/help_sessions_helper.rb
module HelpSessionsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/help_session_requests/_form.html.erb
<%= form_with(model: help_session_request, local: true) do |form| %>
  <% if help_session_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help_session_request.errors.count, "error") %> prohibited this help_session_request from being saved:</h2>

      <ul>
      <% help_session_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :help_session_request_user_id %>
  </div>

  <div class="field">
    <%= form.label :tutor_id %>
    <%= form.number_field :tutor_id, id: :help_session_request_tutor_id %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id, id: :help_session_request_course_id %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start, id: :help_session_request_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end, id: :help_session_request_end %>
  </div>

  <div class="field">
    <%= form.label :accepted %>
    <%= form.check_box :accepted, id: :help_session_request_accepted %>
  </div>

  <div class="field">
    <%= form.label :denied %>
    <%= form.check_box :denied, id: :help_session_request_denied %>
  </div>

  <div class="field">
    <%= form.label :denied_by %>
    <%= form.number_field :denied_by, id: :help_session_request_denied_by %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :help_session_request_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/help_session_requests/edit.html.erb
<h1>Editing Help Session Request</h1>

<%= render 'form', help_session_request: @help_session_request %>

<%= link_to 'Show', @help_session_request %> |
<%= link_to 'Back', help_session_requests_path %>

app/views/help_session_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Help Session Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Tutor</th>
      <th>Course</th>
      <th>Start</th>
      <th>End</th>
      <th>Accepted</th>
      <th>Denied</th>
      <th>Denied by</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @help_session_requests.each do |help_session_request| %>
      <tr>
        <td><%= help_session_request.user_id %></td>
        <td><%= help_session_request.tutor_id %></td>
        <td><%= help_session_request.course_id %></td>
        <td><%= help_session_request.start %></td>
        <td><%= help_session_request.end %></td>
        <td><%= help_session_request.accepted %></td>
        <td><%= help_session_request.denied %></td>
        <td><%= help_session_request.denied_by %></td>
        <td><%= help_session_request.message %></td>
        <td><%= link_to 'Show', help_session_request %></td>
        <td><%= link_to 'Edit', edit_help_session_request_path(help_session_request) %></td>
        <td><%= link_to 'Destroy', help_session_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Help Session Request', new_help_session_request_path %>

app/views/help_session_requests/new.html.erb
<h1>New Help Session Request</h1>

<%= render 'form', help_session_request: @help_session_request %>

<%= link_to 'Back', help_session_requests_path %>

app/views/help_session_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @help_session_request.user_id %>
</p>

<p>
  <strong>Tutor:</strong>
  <%= @help_session_request.tutor_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @help_session_request.course_id %>
</p>

<p>
  <strong>Start:</strong>
  <%= @help_session_request.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @help_session_request.end %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @help_session_request.accepted %>
</p>

<p>
  <strong>Denied:</strong>
  <%= @help_session_request.denied %>
</p>

<p>
  <strong>Denied by:</strong>
  <%= @help_session_request.denied_by %>
</p>

<p>
  <strong>Message:</strong>
  <%= @help_session_request.message %>
</p>

<%= link_to 'Edit', edit_help_session_request_path(@help_session_request) %> |
<%= link_to 'Back', help_session_requests_path %>